language: c

branches:
  only:
  - master

matrix:
  include:
  # Python 3.5 with ghdl llvm
  - env: BUILD_NAME=ACCEPTANCE
    os: linux
    sudo: required
    dist: buster
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gnat zlib1g-dev
    - sudo apt-get install -y llvm-dev libedit-dev
    before_script:
    - cd ..
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-llvm
    - cd build-llvm
    - ../configure --enable-synth --with-llvm-config=llvm-config-7
    - make
    - sudo make install
    - cd ../..

install: true

script:
    - cd libvhdl/test; make all
